{% set version = "0.26.1" %}

package:
  name: fbpic
  version: {{ version }}

source:
  url: https://github.com/fbpic/fbpic/archive/refs/tags/{{ version }}.tar.gz
  sha256: 27d1fd3cf55daee67110e01cf12d90a6ae0017205d116453c2b71b939b49724a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - h5py
    - numba
    - numpy
    - python >={{ python_min }}
    - python-dateutil
    - scipy
# For fast non-MKL FFTs, explore using in the future:
# https://github.com/fbpic/fbpic#installation
# pyfftw

test:
  requires:
    - python {{ python_min }}
  imports:
    - fbpic

about:
  home: https://fbpic.github.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: Fourier-Bessel Particle-In-Cell code (FBPIC)

  description: |
    FBPIC is a Particle-In-Cell (PIC) code for relativistic plasma physics.
    It is especially well-suited for physical simulations of laser-wakefield
    acceleration and plasma-wakefield acceleration, with close-to-cylindrical
    symmetry.
  dev_url: https://github.com/fbpic/fbpic

extra:
  recipe-maintainers:
    - ax3l
    - MKirchen
    - RemiLehe
    - soerenjalas
