{% set version = "0.26.0" %}

package:
  name: fbpic
  version: {{ version }}

source:
  url: https://github.com/fbpic/fbpic/archive/refs/tags/{{ version }}.tar.gz
  sha256: d18727a7bb3139c5ee869ff1ec3e900affee2d383a49568e335ffff1d602145e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - h5py
    - lasy
    - numba
    - numpy
    - pyfftw
    - python >=3.6
    - python-dateutil
    - scipy

test:
  requires:
    - matplotlib
    - python
    - pytest
  source_files:
    - docs/
    - tests/
  imports:
    - fbpic

about:
  home: https://fbpic.github.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: Fourier-Bessel Particle-In-Cell code (FBPIC)

  description: |
    FBPIC is a Particle-In-Cell (PIC) code for relativistic plasma physics.
    It is especially well-suited for physical simulations of laser-wakefield
    acceleration and plasma-wakefield acceleration, with close-to-cylindrical
    symmetry.
  dev_url: https://github.com/fbpic/fbpic

extra:
  recipe-maintainers:
    - ax3l
    - MKirchen
    - RemiLehe
    - soerenjalas
